name: liana
description: Liana learning app.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5

  flutter_bloc: 8.1.3

  injectable: 2.1.2
  get_it: 7.6.0

  freezed_annotation: 2.4.1
  floor: 1.4.2
  flutter_slidable: 3.1.0
  shared_preferences: 2.2.0
  easy_localization: 3.0.2
  flutter_native_splash: 2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
  dart_code_metrics: 5.7.6

  injectable_generator: 2.1.6
  build_runner: 2.4.6
  freezed: 2.4.1
  floor_generator: 1.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
