name: liana
description: Liana learning app.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5

  flutter_bloc: 8.1.3

  injectable: 2.1.2
  get_it: 7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
  dart_code_metrics: 5.7.6

  injectable_generator: 2.1.6
  build_runner: 2.4.6

flutter:
  uses-material-design: true
